#!/usr/bin/env python3
"""
plot_mn9_vs_orn.py

Scatter + error-bar panels of MN9 firing rate vs ORN frequency.

Expect directory layout:
    grn_sweeps/                 ← --experiments-dir (default)
        ├── grn_sweeps_45Hz/    ← auto-selected when --hz=45
        │     ├─ filtered_rates_45Hz_*.csv
        │     └─ filtered_rates_std_45Hz_*.csv
        ├── grn_sweeps_55Hz/
        └── …

The script reads those summary CSVs (generated by `summarize_rates.py`),
derives the control baseline from `sugar_only_<Hz>Hz` columns, and produces
PNG plots in --output-dir.
"""

from __future__ import annotations

import argparse
import re
import warnings
from pathlib import Path
from typing import List, Tuple

import matplotlib.pyplot as plt
import pandas as pd

from constants import CELL_LOOKUP

_MN9_ALIASES = {
    "1": "MN9_LEFT",
    "left": "MN9_LEFT",
    "mn9_left": "MN9_LEFT",
    "l": "MN9_LEFT",
    "2": "MN9_RIGHT",
    "right": "MN9_RIGHT",
    "mn9_right": "MN9_RIGHT",
    "r": "MN9_RIGHT",
}

def to_mn9_key(user_in: str) -> str:
    """Return canonical 'MN9_LEFT' or 'MN9_RIGHT' (or raise)."""
    key = user_in.strip().lower()
    if key == "both":
        return "both"
    canonical = _MN9_ALIASES.get(key, key.upper())
    if canonical not in ("MN9_LEFT", "MN9_RIGHT"):
        raise argparse.ArgumentTypeError(
            f"Unrecognised MN9 selector '{user_in}'. "
            "Use 1/2, left/right, MN9_LEFT/MN9_RIGHT, or both."
        )
    return canonical


# ────────────────────────────────────────────────────────────────────────────
# CLI
# ────────────────────────────────────────────────────────────────────────────
def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description="Plot MN9 firing-rate vs ORN-frequency panels "
                    "from summarize_rates CSV outputs"
    )
    p.add_argument(
        "-e", "--experiments-dir",
        type=Path,
        default=Path("./grn_sweeps"),
        help="Root directory containing *grn_sweeps_<Hz>Hz* sub-folders.",
    )
    p.add_argument(
        "-o", "--output-dir",
        type=Path,
        default=Path("./mn9_vs_orn_plots"),
        help="Directory in which to save PNG plots.",
    )
    p.add_argument(
        "--hz",
        type=int,
        required=True,
        help="Sugar stimulation frequency (Hz).",
    )
    p.add_argument(
        "--mn9",
        type=to_mn9_key,  # ← convert immediately
        default="MN9_LEFT",
        help=('Which MN9 neuron to plot: 1, 2, left, right, '
              'MN9_LEFT, MN9_RIGHT, or both (default: MN9_LEFT).'),
    )
    return p.parse_args()


# ────────────────────────────────────────────────────────────────────────────
# helpers
# ────────────────────────────────────────────────────────────────────────────
def resolve_hz_dir(root: Path, hz: int) -> Path:
    """Return the directory that holds CSVs for the requested Hz."""
    hz_suffix = f"{hz}Hz"

    if root.name.endswith(hz_suffix):
        return root

    matches = [d for d in root.iterdir() if d.is_dir() and d.name.endswith(hz_suffix)]
    if not matches:
        raise FileNotFoundError(
            f"No subdirectory ending with '{hz_suffix}' found beneath {root}"
        )
    if len(matches) > 1:
        raise RuntimeError(
            f"Multiple subdirectories ending with '{hz_suffix}' found under {root}: "
            f"{[m.name for m in matches]} – please disambiguate."
        )
    return matches[0]


def discover_summary_csvs(hz_dir: Path, hz: int) -> Tuple[List[Path], List[Path]]:
    """Locate filtered-rates CSV pairs for the requested sugar Hz."""
    rate_files = list(hz_dir.glob(f"filtered_rates_{hz}Hz_*.csv"))
    std_files = list(hz_dir.glob(f"filtered_rates_std_{hz}Hz_*.csv"))

    if not rate_files:
        raise FileNotFoundError(f"No filtered_rates_{hz}Hz_*.csv found in {hz_dir}")
    if not std_files:
        warnings.warn(
            f"No filtered_rates_std_{hz}Hz_*.csv found in {hz_dir}; "
            "error bars will be suppressed."
        )
    return rate_files, std_files


def load_experiment_rates(
    root: Path, hz: int
) -> Tuple[pd.DataFrame, pd.DataFrame, List[Tuple[str, int, str]]]:
    """
    Merge all summary CSVs and extract (cell_type, ORN_Hz, col_name) metadata.
    """
    hz_dir = resolve_hz_dir(root, hz)
    rate_csvs, std_csvs = discover_summary_csvs(hz_dir, hz)

    # Concatenate rate tables
    df_rate = pd.concat((pd.read_csv(f).set_index("name") for f in rate_csvs), axis=1)

    # Concatenate std tables (or zeros if absent)
    if std_csvs:
        df_std = pd.concat((pd.read_csv(f).set_index("name") for f in std_csvs), axis=1)
    else:
        df_std = pd.DataFrame(index=df_rate.index, columns=df_rate.columns).fillna(0.0)

    # Remove duplicated columns that can appear when multiple CSVs share experiments
    df_rate = df_rate.loc[:, ~df_rate.columns.duplicated()]
    df_std = df_std.loc[:, ~df_std.columns.duplicated()]

    # Experiment metadata from column names
    # ── recognise “…/sugar45Hz_plus_<CELL>_<FREQ>Hz”
    pattern = re.compile(
        rf"sugar{hz}Hz_plus_(?P<cell>.+)_(?P<freq>\d+)Hz$",  # allow “_” inside <cell>
        re.I,
    )

    exp_info: list[tuple[str, int, str]] = []
    for col in df_rate.columns:
        base = col.split("/")[-1]  # drop “experiments/” or “controls/” prefix
        m = pattern.match(base)
        if not m:
            continue  # probably a control column
        exp_info.append((m.group("cell"), int(m.group("freq")), col))

    if not exp_info:
        raise RuntimeError("No experiment columns recognised after parsing.")

    return df_rate, df_std, exp_info


def get_control_stats(
    df_rate: pd.DataFrame, df_std: pd.DataFrame, hz: int, mn9_label: str
) -> Tuple[float, float]:
    """
    Derive control mean ± SD from 'sugar_only_<Hz>Hz' columns.
    If multiple control replicates exist, mean is across replicates and
    SD is their sample standard deviation; otherwise SD falls back to
    the per-run SD stored in df_std.
    """
    pattern = re.compile(rf"sugar_only_{hz}Hz", re.I)
    control_cols = [c for c in df_rate.columns if pattern.search(c)]

    if not control_cols:
        raise RuntimeError(
            f"No control columns matching 'sugar_only_{hz}Hz' found in rate CSVs."
        )

    values = df_rate.loc[mn9_label, control_cols].astype(float)
    mean = float(values.mean())

    if len(control_cols) > 1:
        sd = float(values.std(ddof=0))
    else:
        sd = float(df_std.loc[mn9_label, control_cols[0]])

    return mean, sd


def make_plot(
    df_rate: pd.DataFrame,
    df_std: pd.DataFrame,
    exp_info: List[Tuple[str, int, str]],
    ctrl_mean: float,
    ctrl_sd: float,
    hz: int,
    mn9_label: str,
    out_path: Path,
) -> None:
    """Generate and save a single MN9-vs-ORN plot."""
    cells = sorted({cell for cell, _, _ in exp_info})
    orn_vals = sorted({orn for _, orn, _ in exp_info})
    xmin, xmax = min(orn_vals), max(orn_vals)

    plt.figure(figsize=(8, 6))

    for cell in cells:
        pts = sorted(
            [
                (
                    orn,
                    df_rate.at[mn9_label, col],
                    df_std.at[mn9_label, col],
                    col,  # include column name for annotation
                )
                for c, orn, col in exp_info
                if c == cell
            ],
            key=lambda x: x[0],
        )
        xs, ys, errs, labels = zip(*pts)
        plt.errorbar(xs, ys, yerr=errs, fmt="o-", label=cell)

        # Add small text annotations
        for x, y, label in zip(xs, ys, labels):
            lbl = label.split("_plus_")[-1]  # get <CELL>_<FREQ>Hz
            plt.annotate(lbl, (x, y), textcoords="offset points",
                         xytext=(5, 5), ha='left', fontsize=7, alpha=0.75)

    plt.xlabel("ORN frequency (Hz)")
    plt.ylabel(f"{mn9_label} rate (Hz)")
    plt.title(f"{mn9_label} firing rate vs ORN frequency (sugar {hz} Hz)")
    plt.legend(fontsize="small")
    plt.tight_layout()
    plt.savefig(out_path, dpi=200)
    plt.close()


# ────────────────────────────────────────────────────────────────────────────
# main-level helpers
# ────────────────────────────────────────────────────────────────────────────
# def run_for_mn9(args: argparse.Namespace, mn9_key: str) -> None:
#     df_rate, df_std, exp_info = load_experiment_rates(args.experiments_dir, args.hz)
#     ctrl_mean, ctrl_sd = get_control_stats(df_rate, df_std, args.hz, mn9_key)
#
#     out_file = args.output_dir / f"{mn9_key.lower()}_{args.hz}Hz.png"
#     make_plot(
#         df_rate,
#         df_std,
#         exp_info,
#         ctrl_mean,
#         ctrl_sd,
#         args.hz,
#         mn9_key,
#         out_file,
#     )
#     print(f"Saved plot → {out_file}")

def run_for_mn9(args: argparse.Namespace, mn9_key: str) -> None:
    df_rate, df_std, exp_info = load_experiment_rates(args.experiments_dir, args.hz)
    ctrl_mean, ctrl_sd = get_control_stats(df_rate, df_std, args.hz, mn9_key)

    # Extract ORN cell types from exp_info
    orn_cells = sorted({cell for cell, _, _ in exp_info})
    if len(orn_cells) == 1:
        orn_tag = orn_cells[0]
    else:
        orn_tag = "mixed"

    # Slugify to make filename-safe
    orn_tag = re.sub(r"[^A-Za-z0-9]+", "_", orn_tag).strip("_").lower()

    out_file = args.output_dir / f"{orn_tag}_{args.hz}Hz.png"

    make_plot(
        df_rate,
        df_std,
        exp_info,
        ctrl_mean,
        ctrl_sd,
        args.hz,
        mn9_key,
        out_file,
    )
    print(f"Saved plot → {out_file}")


def main() -> None:
    args = parse_args()
    args.output_dir.mkdir(parents=True, exist_ok=True)

    if args.mn9 == "both":
        run_for_mn9(args, "MN9_LEFT")
        run_for_mn9(args, "MN9_RIGHT")
    else:
        run_for_mn9(args, args.mn9)


if __name__ == "__main__":
    main()